-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.2.13-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for birds
CREATE DATABASE IF NOT EXISTS `birds` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `birds`;


-- Dumping structure for table birds.x_birdbehaviour
CREATE TABLE IF NOT EXISTS `x_birdbehaviour` (
  `bitPosition` tinyint(4) NOT NULL,
  `Behavior` varchar(64) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table birds.x_birdbehaviour: ~6 rows (approximately)
/*!40000 ALTER TABLE `x_birdbehaviour` DISABLE KEYS */;
INSERT INTO `x_birdbehaviour` (`bitPosition`, `Behavior`) VALUES
	(1, 'Human Habitation'),
	(2, 'Swimming or Wading'),
	(4, 'On the ground'),
	(8, 'In trees or bushes'),
	(16, 'On a fence or wire'),
	(32, 'Souring or flying');
/*!40000 ALTER TABLE `x_birdbehaviour` ENABLE KEYS */;


-- Dumping structure for table birds.x_birddescription
CREATE TABLE IF NOT EXISTS `x_birddescription` (
  `birdDescId` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `birdId` smallint(5) unsigned NOT NULL,
  `Description` varchar(1024) NOT NULL,
  `Pictures` varchar(1024) NOT NULL,
  `Sounds` varchar(256) NOT NULL,
  `DistributionMap` varchar(256) NOT NULL,
  PRIMARY KEY (`birdDescId`),
  KEY `birdId` (`birdId`),
  CONSTRAINT `x_birddescription_ibfk_1` FOREIGN KEY (`birdId`) REFERENCES `x_birds` (`birdId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table birds.x_birddescription: ~95 rows (approximately)
/*!40000 ALTER TABLE `x_birddescription` DISABLE KEYS */;
INSERT INTO `x_birddescription` (`birdDescId`, `birdId`, `Description`, `Pictures`, `Sounds`, `DistributionMap`) VALUES
	(2, 3, 'Rather Plump bird with prominent bright red bill and legs. Upperparts blackish-grey and finely barred rufous and white. Underparts dark chestnut, broadly streaked white and deep chestnut breast. Upper half of legs feathered and spurred. Dark tail also barred with white, white tip to tail. Sexes alike but male has blunt spur on tarsus. Juvenile has mottled underparts and less prominent barring. Found in small groups of 6 to 8, upto 30 in non-breeding season. Nests on ground under rock ledges.Feeds on lichen, mosses and shoots. Nests well concealed on hillsides under rocks.', './Media/Snow Partridge/Photos/SnowPartridgeAtTungnathUttarakhandIndia.jpg|Male_1,./Media/Snow Partridge/Photos/snow_partridge__23november2017__tungnath_rudraprayag_district_uttarakhand_india.jpg|Male_2,./Media/Snow Partridge/Photos/snow_partrige_15.jpg|Male_3,', '', ''),
	(3, 4, 'Largish partridge with short,stout, red legs. Different from other snowcocks by extensive white underparts and black streaks on sides. Adult has pale grey-buff upperparts streaked dark grey. White cheeks, chin, throat and breast with dark grey patches on upper neck and breast. Reddish-brown rump and tail. Underparts white with black barring. Sexes alike, but female smaller and duller. Habitat - mostly rocky ridges, slopes and meadows above snowline.', './Media/Tibetan Snowcock/Photos/snowcock2.jpg|Male_1,./Media/Tibetan Snowcock/Photos/_DSC0050_0-L.jpg|Male_2,./Media/Tibetan Snowcock/Photos/472950.jpg|Female_1,', '', ''),
	(4, 5, 'Largish bird, overall grey, black and white with some chestnut streaking that provides good camouflage among rocks.  Dark reddish-brown collar from eyes to neck around white throat. Yellow legs, dark grey bill, brown eyes surrounded by yellowish orbital skin. Sexes alike, female smaller , male has tarsal spurs. Juvenile paler, marked with conspicuous white supercilium. Habitat - Alpine meadows, rocky country above treeline.', './Media/Himalyan Snowcock/Photos/himalayan_snowcockdsc_3847obp.jpg|Male_1,./Media/Himalyan Snowcock/Photos/10672257296_9a0ee969be_b.jpg|Male_2,', '', ''),
	(5, 6, 'Plumpish medium sized bird, overall greyish, buff brown with distinct black band running from eye to base of neck. Whitish face and throat; grey head and breast and black gorget across forehead and eyes. Flanks prominently barred black and white with tinge of brown; bright red bill and legs. Sexes similar but female smaller. Juvenile smaller and mottled brown-grey and slight brown barring on flanks. Small groups forage on open scrub and rock-covered hillside, sometimes cultivation.', './Media/Chukar Partridge/Photos/perdrix.choukar.auau.3g.jpg|Male_1,./Media/Chukar Partridge/Photos/Chukar partridge alectoris chukar.jpg|Male_2,./Media/Chukar Partridge/Photos/chukar-partridge_juvenile.jpg|Juvenile_1,', '', ''),
	(6, 7, 'Handsome jet-black bird with sub tail. Upperparts and flanks spotted white and fulvous, white cheek patch; chestnut collar, belly and undertail-coverts; brownish-red legs. Female similar to male, but paler with wider brown bars on lower back, white cheek patch and chestnut collar missing. Singly; or in small parties in high grass and edges of water; secretive, fast runners on ground. Nests in grass-lined depression in  bare ground.', './Media/Black  Francolin/Photos/black_frankolin.jpg|Male_1,./Media/Black  Francolin/Photos/Black-francolin-Male.jpg|Male_2,./Media/Black  Francolin/Photos/Black_Francoline_Female.jpg|Female_1,', '', ''),
	(7, 8, 'Medium-sized profusely marked bird. Rufous face; chestnut head and throat. Neck and underparts densely spotted white; white rump and tail finely barred with black; yellowish orange legs.Female paler compared to male and no spurs on legs. Skulking,shy and secretive; not easily flushed. Rarely flies, roosts in trees. Feeds on grain, grass and insects. Noisy when breeding during South West monsoon.', './Media/Painted Francolin/Photos/painted_francolinimg_5388.jpg|Male_1,./Media/Painted Francolin/Photos/Painted_Francolin_female.jpg|Female_1,', '', './Media/Painted Francolin/Map/[object Object]'),
	(8, 9, 'Medium-sized greyish-brown partridge with spear-shaped buff streaks. Pale face bordered with black gular-band; orange cheeks, throat and forehead. Wings chestnut with lighter streaking. Found in open scrubs, grass, cultivation. Easily flushed from bushes making the whistling noises as they do. Forages in pairs.', './Media/Gray Francolin/Photos/grey_francolin_sept_01_2013.jpg|Image_1,./Media/Gray Francolin/Photos/Grey_Francolin_Tal_Chappar_Churu_Rajasthan_India_14.02.2013.jpg|Image_2,', '', ''),
	(9, 10, 'Breeding Male crimson and brown, spotted white on wings and white tipped tail. Female brown above, spotted on wings; crimson rump; dull white throat; buff grey breast and dull below. Non-breeding male similar to female, but more grey throat and breast distinctive. In small flocks often with other weavers; partial to tall grass,scrubs,gardens, sugarcane fields preferably around well-watered areas. Active and vibrant, rather confiding.', './Media/Red Avadavat/Photos/red_avadavats_male_breeding.jpg|Breeding Male,./Media/Red Avadavat/Photos/red_avadavat_female.jpg|Female,./Media/Red Avadavat/Photos/red-avadavat-male-juvenile-800x600.jpg|Non-breeding Male,', '', ''),
	(10, 11, 'Overall dull bird, both in colour and demeanour. Sexes alike. Dull brown above with white rump; very dark almost black wings; pointed tail; pale buff-white below. Thick grey-blue beak striking. Gregarious; mostly keeps to scrubs in open country; feeds on ground and standing crop, especially millet. Prefers dry areas unlike other Munias.', './Media/Indian Silverbill/Photos/Indian_Silverbill.jpg|Image_1,./Media/Indian Silverbill/Photos/Indian_Silverbill_Rajarhat_KolkataOutskirts_0001.jpg|Image_2,', '', ''),
	(11, 12, 'Chocolate-brown upperparts; olive-yellow, pointed tail, chestnut sides of face,chin and throat. Silvery-white underparts; thickly speckled with dark brown on breast, flanks and part of belly. Speckles are absent during winter and most of summer; rainy season being the breeding season. Pairs often spotted building nests in buildings with grass and palm leaves. Birds are sociable moving in flocks often with other munias and weavers. Feeds on ground and low bushes, rests in trees. ', './Media/Scaly Breasted Munia/Photos/Scaly-breasted Munia.jpg|Image_1,./Media/Scaly Breasted Munia/Photos/Scaly_breasted_Munia_Immature.jpg|Immature,', '', ''),
	(12, 13, 'Slim, dark munia with short thick conical beak; dark brown head,throat,upper breast, mantle, wings, tail, vent, white belly and white patch on lower back, wedge-shaped tail. Himalayan race has more rufous brown on face. In small family parties when breeding, otherwise large flocks; communal rooster; with other weavers and munias. Forages on ground or on stalks of seed-bearing grass and crops.', './Media/White Rumped Munia/Photos/White-rumped_munia.jpg|Image_1,./Media/White Rumped Munia/Photos/White-rumped_munia_Himalayan_Race.jpg|Himalayan_Race,', '', ''),
	(13, 14, 'Tiny, green weaver with distinct striped flanks. Upperparts green, with black tail; yellow underparts, paler throat.Female has more brown in upperparts,red bill. Feeds on small seeds or invertebrates on ground. Small flocks, nests in thick cover. Globally threatened; endemic and rare breeding resident in a few sites in NC peninsular India. Habitat is grass, scrubs and sugarcane often near water.', './Media/Green Avadavat/Photos/green_munia.jpg|Male_1,./Media/Green Avadavat/Photos/GAPair.jpg|Pair,', '', ''),
	(14, 15, 'Brown-black head, more brownish on crown, nape and mantle, brown-black rump spotted or finely barred white; lower breast, belly and flanks creamy-white spotted with deep brown. Short, stout bill with dark upper mandible and paler lower mandible. Sexes alike. Gregarious, feeds mainly on seeds.', './Media/Black throated Munia/Photos/Black-throated_Munia.jpg|Image_1,./Media/Black throated Munia/Photos/blackthroated_muniaa.jpg|Image_2,', '', ''),
	(15, 16, 'Male has black head, throat, breast, center of belly and thighs;rufous-chestnut back and rump; white upper belly and sides of underbody. Female similar to male but has deep brown undertail-coverts. Gregarious, except when breeding; prefers reed beds and cultivation, especially where flooded. During breeding season(monsoon), often seen along with streaked weaver; feeds on ground.', './Media/Black headed Munia/Photos/Tricoloured_munia_.jpg|Image_1,./Media/Black headed Munia/Photos/Tricolor_Munia.jpg|Image_2,', '', ''),
	(16, 17, 'Small munia with black head,nape,crown,throat and upper breast. Striking silvery-blue bill. Chestnut upperparts; rusty-orange rump and tail. Sexes alike.Feeds on seeds and invertebrates on ground, actively in flocks. Often very confiding, nests in reeds.', './Media/Chestnut Munia/Photos/Chestnut_Munia.jpg|Image_1,./Media/Chestnut Munia/Photos/Chestnut-munia400x400.jpg|Image_2,', '', ''),
	(17, 18, 'Male grey above; broad dark stripe through eyes to ears; black wings,tail; greyish breast whitish below. Female barred grey and white below; paler stripe through eyes. In pairs or small flocks; characteristic flight over forest; few wing beats and glide; often calls in flight; flicks wings on perching; keeps to upper branches, may descend into bushes; very active and noisy in breeding season(March-June).', './Media/Large Cuckooshrike/Photos/Large_Cuckooshrike_Male.jpg|Male_1,./Media/Large Cuckooshrike/Photos/Large_Cuckooshrike_female.jpg|Female_1,./Media/Large Cuckooshrike/Photos/large_cuckooshrike_2516.jpg|Female_2,', '', ''),
	(18, 19, 'Similar to Large Cuckooshrike but smaller and deeper grey. Male has dark grey throat and breast;broad charcoal-grey barring on rest of underparts. Female entirely barred from chin to vent.Juvenile scaly above with pale rufous tips and fringes to greater coverts and tertials, barred underparts and rufous cast to throat and breast. Immature similar to female but rufous throat and breast. Found in Andaman Islands. ', './Media/Bar-belied Cuckooshrike/Photos/barbellied_cuckooshrike4131.jpg|Male_1,./Media/Bar-belied Cuckooshrike/Photos/barbellied_cuckooshrike_f.jpg|Female_1,', '', ''),
	(19, 20, 'Medium-sized, dark cuckooshrike with unbarred grey underparts. male, dark grey above with contrasting black wings and tail. Underside of tail shows broad white feather-tips.Female paler with faint barring on underparts. feeds on invertebrates on in canopy and undergrowth; singly or in pairs. Joins mixed hunting groups. Undulating flight, nests in trees.', './Media/Black-winged Cuckooshrike/Photos/Black-winged_Cuckooshrike_M.jpg|Male_1,./Media/Black-winged Cuckooshrike/Photos/Black_winged_cuckooshrike_Fem.jpg|Female_1,', '', ''),
	(20, 21, 'Male of grey plumage; black head, wings and tail.Tail is white-tipped, except on middle feathers; pale grey below breast, whiter on abdomen, vent.Female has brown plumage; whitish-buff below, barred dark brown till abdomen; lacks black head.Solitary or in pairs, only occasionally several together; often part of mixed hunting bands; keeps for most part to leafy, upper branches. Probes foliage for insects, methodically checks foliage before flying off.', './Media/Black-headed Cuckooshrike/Photos/blackheaded_cuckooshrike_male.jpg|Male_1,./Media/Black-headed Cuckooshrike/Photos/Black-headed cuckooshrike -Male.jpg|Male_2,./Media/Black-headed Cuckooshrike/Photos/blackheaded_cuckooshrike_female.jpg|Female_1,', '', ''),
	(21, 22, 'Boldly patterned with whitish underparts, tinged grey. Male has white face, black eye-stripe and white supercilium; black crown, nape and mantle. Black tail with white tip; white edges to wing coverts; grey rump. Female has more grey and faintly barred underparts.The race Lalage nigra davisoni is found in Andaman and Nicobar islands.', './Media/Pied Triller/Photos/Pied_Triller_male.jpg|Male_1,./Media/Pied Triller/Photos/Piedtrillerfemale.jpg|Female_1,', '', ''),
	(22, 23, 'Male greenish above (rich black above with yellowish rump in summer breeding plumage); black wings and tail; two white wing-bars; bright yellow underbody. Female has yellow green plumage; white wing-bars; greenish-brown wings. Pairs keep to leafy branches often with other small birds; moves energetically amidst branches in hunt for insects, caterpillars; rich call notes often a giveaway of its presence in an area.Renowned vocalist, wide range of rich whistling notes. Common call a long drawn wheeeee chu.', './Media/Common Iora/Photos/Common-Iora.JPG|Male_1,./Media/Common Iora/Photos/Common Iora 1.JPG|Breeding Male,./Media/Common Iora/Photos/Common_Iora_Aegithina_tiphia.jpg|Female,', '', ''),
	(23, 24, 'Male has rich grass-green plumage; hooked heavy red beak; deep red shoulder patch; rose-pink collar and black stripe from lower mandible to collar distinctive. Female smaller and lack collar and stripe.Yellow undertail in both sexes. Seen in small flocks and large gatherings; feeds on fruiting trees in orchards and on standing crops; strong flier; roosts along with other birds at favoured sites.', './Media/Alexandrine Parakeet/Photos/PSX_20181106_173537.jpg|Male_and_female,./Media/Alexandrine Parakeet/Photos/PSX_20181106_173823.jpg|Female,', '', ''),
	(24, 25, 'Male has grass-green plumage;short,hooked,red beak; rosy-pink and black collar distinctive(obtained only during the 3rd year).Female lacks collar; instead pale emerald green around neck.Gregarious;large flocks causing extensive damage to standing crops, orchards and fruit trees. Also raids grain depots and markets, large roosting colonies often along with mynas and crows', './Media/Rose-ringed parakeet/Photos/Rose-ringed_Parakeet_eating_leaves.jpg|Male_front,./Media/Rose-ringed parakeet/Photos/Rose Ringed Parakeet_male.jpg|Male_back,./Media/Rose-ringed parakeet/Photos/rose_ringed_parakeet_male_female.jpg|Male_and_female,', '', ''),
	(25, 26, 'Adult of both sexes overall green, washed blue; bluish-grey head; blackish chin; wide stripe across lower cheeks; blue-green band around neck bordered with fine black line;base of tail green graduating to deep blue;tipped with bright yellow; red upper mandible and lower yellow; pale yellow eyes. Male has prominent maroon patch on inner median wing-coverts and long central tail feathers. Female lacks wing patch but has central tail feathers. Juvenile has greyish-green face; dull green head;faint pale green stripe below cheeks to crown; wing patch is absent; short tail;orange bill;grey eye.\r\n\r\nFound between 600-2500 m in the Himalayas; descends much lower in winter.', './Media/Slaty-headed Parakeet/Photos/Slaty_headed_Parakeet_male.jpg|Male,./Media/Slaty-headed Parakeet/Photos/Slaty_Headed_Female.jpg|Female,', '', ''),
	(26, 27, 'Adult of both sexes overall yellowish-green; dark grey head; black chin; wide stripe across lower cheek narrowing to thin line around neck; small maroon patch on inner median wing-coverts; central tail feathers long(shorter in female); bluish-purple upper tail tipped with yellow or white.Female lacks maroon shoulder patch. Immature has dark bill; greyish-green face; faint pale green band below cheeks to hind crown; wing patch absent. Short tail,orange bill;orange-grey eye.\r\n\r\nResident of e Himalayas. Forests, open woodlands and city gardens.', './Media/Grey-headed Parakeet/Photos/Grey-headed-Parakeet_Male.jpg|Male,./Media/Grey-headed Parakeet/Photos/Grey_headed-parakeet_Immature.jpg|Immature,', '', ''),
	(27, 28, 'Male has yellowish-green plumage; plum-red head washed purplish-blue on hind-crown;black chin strap;black and bluish-green collar; dark red dot on inner median wing coverts; white tips to tail feathers distinctive.Female dull grey head,yellow collar; shoulder patch non-existent.In pairs or small flocks;arboreal,but descends into cultivation in forest clearings and outskirts; sometimes huge gatherings in cultivation. Strong darting flight over forest.', './Media/Plum-headed Parakeet/Photos/plum-headed-parakeet_female.jpg|Male,./Media/Plum-headed Parakeet/Photos/plum-headed-female.jpg|Female,', '', ''),
	(28, 29, 'Male has rosy-pink cheeks,forehead and ear coverts; pale purplish-blue nape and crown; black chin stripe graduating to thin line on hind-neck;dark red dot on inner median wing coverts. Central tail feathers blue-tipped with pale yellow; side tail feathers greenish-yellow, tipped pale yellow. Orangish-yellow upper mandible,dark grey lower mandible; pale yellow eye. female has dull blue-grey head, dull yellowish-green collar and smaller shoulder spot.Juvenile has green head,shorter tail,pale yellow bill and grey eye.Gregarious and noisy. \r\n\r\nFound in open forests.', './Media/Blossom-headed Parakeet/Photos/Blossom-headed-parakeet_male.jpg|Male,./Media/Blossom-headed Parakeet/Photos/Blossom-headed-parakeet_female.jpg|Female,', '', ''),
	(29, 31, 'Lavender-grey head and mantle, broad emerald green collar and deep cobalt blue tail.Broad black chin stripe; blue tail tipped yellow.Male has scarlet red upper mandible and brown lower mandible.Female has black beak and deep green cheek stripe.Immature similar to female but with shorter tail feathers, with mainly green plumage and dark red bill.\r\nIt is a resident endemic breeder in Sri Lanka', './Media/Layards Parakeet/Photos/layards_parakeet_male.jpg|Male,./Media/Layards Parakeet/Photos/Layards_Parakeet_female.jpg|Female,', './Media/Layards Parakeet/Sounds/XC311462 - Layard\'s Parakeet - Psittacula calthrapae.mp3', ''),
	(30, 32, 'Very large Tibetan Parakeet with purple head and underparts; large bill with black broad mustache. Male has red upper mandible; it is black in female.Juvenile duller with greyish head with paler lore-line and mustache;some green feathers on face and some rusty-brown feathers below.Blue wing-lining visible in flight. Frequently visits nest holes in tall trees.\r\nEvidently common in border regions of NE Arunachal Pradesh.\r\nLittle know habitat. Typically occurs in small flocks.Seen in Mishmi hills in September.', './Media/Derbyan Parakeet/Photos/Derbyan_Parakeet_female.jpg|Female,./Media/Derbyan Parakeet/Photos/Derbyan_Parakeet_Male_female.jpg|Male_and_female,', '', ''),
	(31, 33, 'Male mainly yellowish-green in colour with buff-grey head, black forehead and brown black chin-stripe and blackish flight feathers with bluish edges.Female has bluish-grey tinge to crown and nape and black rather than red upper mandible.\r\n\r\nRange: Nicobar Islands\r\nHabitat: Tall forests', './Media/Nicobar Parakeet/Photos/nicobar_parakeet_male.jpg|Male,./Media/Nicobar Parakeet/Photos/nicobar_parakeet_female.jpg|Female,', '', ''),
	(32, 34, 'Typical parakeet with pinkish cheeks,green crown and broad black chin-stripe.Back often with bluish wash and very long blue tail. Upper mandible red(black in female), lower mandible black. Female more green above. Immature uniform green with fainter chin stripe. Raids fruits and cereal crops. Acrobatic and very fast flight. Nests in tree holes.\r\nCommon breeding resident and restricted to Andaman and Nicobar Islands. Found in forests and plantations.', './Media/Long-tailed Parakeet/Photos/long-tailed-parakeet_male.jpg|Male,./Media/Long-tailed Parakeet/Photos/Long-tailed-Parakeet_Male_Female.jpg|Male_and_female,', '', ''),
	(33, 35, 'Adult has green upperparts; green to yellow median wing-coverts forming large patch on wing; grey head with varying tinges of blue; black narrow line from forehead to eyes, black wide band across lower cheek; salmon-pink throat to upper abdomen duller in female. Green lower abdomen to undertail coverts with blue suffusion; blue central tail feathers tipped with yellow/green. Bill coral red, eye pale yellow. Juvenile has green crown and underparts; dark brown lower cheeks; brown/grey wash on green sides of head; green median wing-coverts \r\nmargin-ed with yellow/green.Tail short, bill pale red and eye grey.\r\n\r\nHabitat: Foothill forests\r\nscarce breeding resident in N foothills east from Uttarakhand.', './Media/Red-breasted Parakeet/Photos/Red-breasted-parakeet-male-back.jpg|Male_back,./Media/Red-breasted Parakeet/Photos/Red_breasted-Parakeet_male_front.jpg|Male_front,./Media/Red-breasted Parakeet/Photos/Red_breasted-Parakeet_juvenile_adult.jpg|Juvenile_with_adult,', '', ''),
	(34, 36, 'Small short-tailed and primarily emerald-green plumaged bird with blue patch on throat; red rump and uppertail coverts; red bill; white eye.Female similar to male but little or no blue on throat. Juvenile similar to adult but has greyish-green on forehead and cheeks, no blue on throat; dull red rump washed green; pale orange bill; brown eye.Unique for its ability to sleep upside down.Very arboreal.', './Media/Vernal Hanging Parrot/Photos/Vernal_Hanging_Parrot_Male.jpg|Male,./Media/Vernal Hanging Parrot/Photos/Vernal_Hanging_Parrot_female.jpg|Female,', '', ''),
	(35, 37, 'Very similar to Vernal Hanging Parrot but has larger bill, crimson forehead and crown, golden-orange cast to nape and mantle, turquoise wash on throat(like Vernal). Immature has greyish-green forehead, orange cast to green crown with few splashes of red and faint turquoise wash to throat.\r\n\r\nHabitat: Broadleaved evergreen and moist deciduous forests.', './Media/Sri Lanka Hanging Parrot/Photos/sri_lanka_hanging_parrot_male.jpg|Male,./Media/Sri Lanka Hanging Parrot/Photos/SriLanka_Hanging_Parrot_Male_female.jpg|Male_and_female,', '', ''),
	(36, 38, 'Large stocky dove with grey-black spotted patch on neck sides. Rufous-brown back and scapulars, with black markings diagnostic; slaty-grey lower back, rump,whitish border to roundish tail, best seen when fanned during landing.Sexes alike,in pairs or loose parties, occasionally solitary birds; feeds mostly on ground; rests during hot hours in leafy branches; perches on overhead wires.', './Media/Oriental Turtle Dove/Photos/Oriental Turtle Dove 2.JPG|Male_1,./Media/Oriental Turtle Dove/Photos/oriental_turtle_dove.jpg|Male_2,', '', ''),
	(37, 40, 'Male has deep ash-grey head; black hindneck-collar; rich wine-red back; slaty grey-brown lower back,rump and uppertail; whitish tip to all but central tail feathers. Female much like Eurasian Collared Dove,but smaller in size and more brownish coloration distinctive.Solitary or in pairs or small parties; associates with other doves but less common. Feeds on ground, gleaning on harvested croplands;perches and suns on leafless branches and overhead wires.', './Media/Red Collared Dove/Photos/Red_Collared_Dove.jpg|Male,./Media/Red Collared Dove/Photos/red_collared_dove_back.jpg|Male_back,./Media/Red Collared Dove/Photos/Red_Collared_Dove_Female.jpg|Female,', '', ''),
	(38, 41, 'Slender dove with long wedged tail. Grey and pink-brown above,white-spotted black hind neck collar(chessboard) diagnostic. Dark tail with broad white tips to outer feather seen in flight, brown breast merging on to white belly. Sexes alike, juvenile barred above and lacks chessboard neck. In pairs or small parties on ground; flying further on intrusion; quite tame and confiding in many areas; drinks often. At harvest times seen along with other doves in immense gatherings.', './Media/Spotted Dove/Photos/Spotted_Dove_Back.JPG|Male_back,./Media/Spotted Dove/Photos/Spotted_Dove_Front.JPG|Male_Front,', '', ''),
	(39, 42, 'Pinkish grey-brown plumage with black and white chessboard on front neck; white tips to outer tail feathers and broad grey wing patches best seen in flight; small size distinctive. Sexes alike. In pairs or small flocks; associates freely with other doves in huge gatherings at harvest time;feeds mostly on ground, walking about silently.', './Media/Laughing Dove/Photos/Laughing_dove_front.jpg|Male_front,./Media/Laughing Dove/Photos/Laughing_dove_back.JPG|Male_back,', '', ''),
	(40, 43, 'Bronze emerald green upperbody; white forehead and eyebrow; grey crown and neck, white on wing shoulder and across lower back; whitish rump diagnostic in flight; rich pinkish-brown below; coral beak and pink-red legs. Sexes alike. Solitary or in pairs; moves on forest paths and clearings or darts almost blindly through trees, usually under 5 meters off ground; difficult to spot on ground.\r\nHabitat: Forests,bamboo clearings; foothills', './Media/Emerald Dove/Photos/Emerald_Dove_on_ground.JPG|On the ground,./Media/Emerald Dove/Photos/Emerald_Dove_Bird_Bath.JPG|At Bird-bath,', '', ''),
	(41, 44, 'Large and distinctive dove with slim body and long graduated tail; reddish-brown upperparts and tail heavily barred brown. Male has paler unbarred buff head and underparts; iridescent green on nape and crown; some barring on neck sides and upper breast; female has barring on underparts and some iridescence on neck sides and nape. Forest-dwelling and often acrobatic in effort to reach food. Most often glimpsed flying between trees; feeds mostly on fruits and berries.\r\nHabitat: Dense broadleaved evergreen,tropical,sub-tropical and temperate forest; secondary growth.', './Media/Barred Cuckoo Dove/Photos/Barred_Cuckoo_dove_male.jpg|Male,./Media/Barred Cuckoo Dove/Photos/Barred_Cuckoo-Dove_Female.jpg|Female,', '', ''),
	(42, 45, 'Large cuckoo dove with small head and slim body,long graduated tail. Head and underparts reddish-brown in colour. Flight shows rufous flashes across inner webs of primaries and rufous underwing-coverts. Male has brown barring across breast and belly and unmarked head.\r\nHabitat: Andaman and Nicobar Islands;only cuckoo-dove in these islands', './Media/Andaman Cuckoo Dove/Photos/Andaman_Cuckoo-Dove_Male_Front.jpg|Male_front,./Media/Andaman Cuckoo Dove/Photos/Andaman_Cuckoo_dove_male_Back.jpg|Male_back,./Media/Andaman Cuckoo Dove/Photos/Andaman_Cuckoo_dove_female.jpg|Female,', '', ''),
	(43, 46, 'Small olive-green bird with broad black tail tipped white. Upperparts mostly olive with fine, white wing-bar; yellow head; olive rear crown; dark mask and eye-stripes. Underparts yellow. Very active, forages for insects in foliage; frequently catches flies and returns to perch.\r\nHabitat: Mainly broad leaved forests,often near water.', './Media/Yellow-bellied Fantail/Photos/Yellow-bellied_fantail_male_front.jpg|Male_front,./Media/Yellow-bellied Fantail/Photos/yellow-bellied_fantail_male.jpg|Male_side,./Media/Yellow-bellied Fantail/Photos/yellow-bellied_Fantail_female.jpg|Female,', '', ''),
	(44, 47, 'Distinguished by dark fan-shaped tail edged with white. Overall brown and white bird with broad white tip to tail(except 2 central feathers) ; white throat and supercilium. The Himalayan race has slaty grey upperparts and underparts and black eye mask. The peninsular race has dark grey upperparts, whitish underparts and grey breast band. Sexes alike.\r\nHabitat: Shaded forests, scrubs and gardens, favoring well-wooded ravines.', './Media/White-throated Fantail/Photos/White-throated_Fantail.jpg|Male,./Media/White-throated Fantail/Photos/White-throated fantail_tail_fanned.jpg|Male_Tail_fanned,', '', ''),
	(45, 48, 'Characteristic habit of fanning black and white tail and flicking wings.Dark brown upperparts, black crown and face sides. White forehead and nape; 2 wing bars with white spots; tail tipped white; white throat; breast and underparts. Sexes alike,but female slightly duller.Solitary or in pairs.Flits about constantly in lower and middle branches,makes short dashes to hunt; tame and confiding.\r\nHabitat: Forests,orchards, gardens; tree-dotted cultivation.', './Media/White-browed fantail/Photos/White-browed_Fantail.jpg|Male,./Media/White-browed fantail/Photos/white_browed_fantail_front.jpg|Male_front,./Media/White-browed fantail/Photos/white_browed_fantail_tail_fanned.jpg|Male_tail_fanned,', '', ''),
	(46, 51, 'Adult has short white supercilium, slaty grey crown,face,wings,tail and underparts. White spotted  black breast, buff belly, white throat. Juvenile similar to adult with rufous spots on wing coverts. Characteristic fanning of tail as it moves through bushes. Call includes a scratchy check repeated irregularly, often in rapid series. Found alongwith white-browed fantail in NE peninsula.\r\nHabitat: Wooded areas, secondary forest.', './Media/Spot-breasted Fantail/Photos/Spot-breasted_fantail.JPG|Male,./Media/Spot-breasted Fantail/Photos/Spot breasted Fantail_Male.JPG|Male_side,./Media/Spot-breasted Fantail/Photos/Spot breasted Fantail_tail_fanned.JPG|Male_tail_fanned,', '', ''),
	(47, 52, 'Stout short-tailed bird with powerful legs and feet;small ashy-grey head,reddish face with exposed skin and small rufous crest. Largely dark brown, underparts grey; female more grey. Immature birds lack bare red skin patch. Often found in pairs or mixed droves with young. Strong runners, mostly spending time on ground,flying reluctantly to take shelter on nearby trees. Breeds all year round. Female lays eggs in mounds of rotting vegetation. Feeds on vegetation, seeds, insects and snails.\r\nHabitat: Near dense undergrowth of evergreen forests on sandy beaches.', './Media/Nicobar Megapode/Photos/Nicobar Megapode.jpg|Male,./Media/Nicobar Megapode/Photos/nicobar_megapode.jpg|Male_and_Female,', '', ''),
	(48, 53, 'Similar to Red-collared Dove female but larger with different tail pattern. Grey-brown plumage; lilac wash about head and neck; black half collar on hindneck diagnostic; broad whitish tips to brown tail feathers, seen as terminal band when fanned during landing. Dull lilac breast and ash-grey underbody. Sexes alike. Small parties, when not breeding; often associates with other doves; large gatherings glean in cultivated country; strong flier; chases intruders in territory.', './Media/Eurasian Collared Dove/Photos/Eurasian_Collared_dove.jpg|Male,./Media/Eurasian Collared Dove/Photos/Eurasian_Collared-Dove_front.jpg|Male_front,', '', ''),
	(49, 54, 'Male has lilac-blue plumage; black patch on nape and gorget on breast; slightly black scaly markings on crown; sooty on wings and tail; white below breast. Female ash-blue,duller; lacks black on nape and breast. Solitary or in pairs in forests,often amidst mixed hunting parties; extremely active and fidgety, flits and flutters about,often fans tail slightly; calls often on the move. Calls are often its first indication of presence.\r\nHabitat: Forests,bamboos and gardens.', './Media/Black-naped Monarch/Photos/Monarch_Flycatcher_Male.JPG|Male,./Media/Black-naped Monarch/Photos/Monarch_Flycatcher_Male_back.JPG|Male_back,./Media/Black-naped Monarch/Photos/Monarch_Flycatcher_Female.JPG|Female,', '', ''),
	(58, 63, 'Glossy blue-black head,crest and throat; balck in wings;silvery-white body;white underparts and long white tail-streamers. Male occurs in 2 morphs: rufous phase has white parts replaced by rufous-chestnut, white phase is variable between white and rufous but predominantly white plumage. Female and juvenile lack tail-streamers, have shorter crest; rufous above; ashy-grey throat and nuchal-collar; whitish below. Short legs; tends to sit upright on perch. Solitary or in pairs; makes short sallies,flits through trees,tail-streamers floating. Strictly arboreal,sometimes descending to taller bushes;cheerful disposition.', './Media/Indian Paradise Flycatcher/Photos/Indian_Paradise_Flycatcher_White_Phase.JPG|Male_White_Phase,./Media/Indian Paradise Flycatcher/Photos/Indian_Paradise_Flycatcher_rufous_phase.jpg|Male_Rufous_phase,./Media/Indian Paradise Flycatcher/Photos/Indian Paradise Flycatcher Female.JPG|Female,./Media/Indian Paradise Flycatcher/Photos/Indian_Paradise-flycatcher_(Female).jpg|Female_side,./Media/Indian Paradise Flycatcher/Photos/Indian_Paradise_Flycatcher_Male_Full.jpg|Male_Full,', './Media/Indian Paradise Flycatcher/Sounds/XC413778 - Indian Paradise Flycatcher - Terpsiphone paradisi.mp3', ''),
	(59, 64, 'Male has bright golden-yellow plumage,black stripe through eye; black wings and center of tail. Female yellow-green above;has brownish-green wings;dirty white below,streaked brown. Juvenile similar to female. Solitary or in pairs; arboreal,sometimes moving with other birds in upper branches. Regularly visits fruiting and flowering trees;hunts insects in leafy branches. Usually heard,surprisingly not often seen,despite bright colour; seen only when emerges on bare branches or flies across.\r\nHabitat: Forests,orchards and gardens around habitation.', './Media/Golden Oriole/Photos/Golden_Oriole_Male_Front.jpg|Male_front,./Media/Golden Oriole/Photos/Golden_Oriole_Male_Back.jpg|Male_back,./Media/Golden Oriole/Photos/Golden oriole_Female.jpg|Female,', './Media/Golden Oriole/Sounds/XC201337 - Indian Golden Oriole - Oriolus kundoo.mp3', ''),
	(60, 65, 'Adult male has golden-yellow head; broad black band extending from lores around eye and across back of head. Very similar to Black-naped,but distinguished by longer and more downward curved bill and narrower nape-band. Olive-yellow wing coverts and panel across secondaries. Female has more olive tinge to yellow in plumage and some indistinct barring in underparts. Juvenile hard to distinguish from Black-naped except for longer bill.\r\nHabitat: Well-wooded areas,groves,large trees in open country. Winters lower in broadleaved forests.', './Media/Slender-billed Oriole/Photos/slenderbilled_oriole_male.jpg|Male,./Media/Slender-billed Oriole/Photos/slenderbilled_oriole_male_side.jpg|Male_side,./Media/Slender-billed Oriole/Photos/slender-billed_oriole_female.jpg|Female,', './Media/Slender-billed Oriole/Sounds/XC208898 - Slender-billed Oriole - Oriolus tenuirostris invisus.mp3', ''),
	(61, 66, 'Easily differentiated from Golden Oriole by broad black eye-stripe continuing to join on nape and much stouter bill. Female more greenish or olive on mantle. Overall yellow with black in flight feathers and black tail with yellow patches.Juvenile has some streaking on underparts and more diffused eye-stripe. Indulges in high-speed aerial chases. Raids nests of other birds, taking their eggs and chicks.\r\nHabitat: Rubber Plantations', './Media/Black-naped Oriole/Photos/Black_naped_Oriole_Male.jpg|Male,./Media/Black-naped Oriole/Photos/Black_naped_Oriole_female.jpg|Female,./Media/Black-naped Oriole/Photos/Black_naped_Oriole_Juvenile.jpg|Juvenile,', '', ''),
	(62, 67, 'Golden-yellow plumage;black head diagnostic;black and yellow wings and tail; deep pink-red beak seen at close quarters. Sexes alike. In pairs or small parties;strictly arboreal,only rarely descending to lower bushes or ground. Active and lively; moves a lot in forests,birds chase one another, rich colours striking against green or brown of forests; very vocal; associates with other birds in mixed parties,frequently joining mixed hunting groups. Visits fruiting and flowering trees.\r\nHabitat: Forests,orchards,gardens, often amidst habitation.', './Media/Black-hooded Oriole/Photos/Black Hooded Oriole.jpg|Male,./Media/Black-hooded Oriole/Photos/Black hooded Oriole_back.jpg|Male_back,', './Media/Black-hooded Oriole/Sounds/XC425603 - Black-hooded Oriole - Oriolus xanthornus.mp3', ''),
	(63, 68, 'Adult has maroon body,black head and wings. Deep scarlet-red tail; strong curved grey bill; startling white iris. Female has blackish upperparts, dull maroon back; white underparts heavily streaked maroonish-brown. Solitary or in pairs often in mixed hunting parties. Well hidden in canopy; feeds on invertebrates,nectar and fruits.\r\nHabitat:Subtropical or tropical moist lowland forests.', './Media/Maroon Oriole/Photos/maroon-oriole_male_side.jpg|Male,./Media/Maroon Oriole/Photos/Maroon_oriole.jpg|Male_back,./Media/Maroon Oriole/Photos/Maroon_Oriole_Female.jpg|Female,', './Media/Maroon Oriole/Sounds/XC450596 - Maroon Oriole - Oriolus traillii.mp3', ''),
	(64, 69, 'Glossy black plumage,long deeply forked-tail. Diagnostic white spot at base of bill. Sexes alike. Immature can resemble White-b bellied drongo. Usually solitary,sometimes in small parties; keeps lookout from exposed perch. Most common bird seen on rail and road travel in India; drops to ground to capture prey; launches aerial sallies. Rides atop grazing cattle; follows tractors,grass-cutters and fires; to hunt scores of insects on the ground disturbed by them. Bold and aggressive species with several birds nesting in same tree.\r\nHabitat: Open country, orchards and cultivation.', './Media/Black Drongo/Photos/Black_Drongo.JPG|Male_front,./Media/Black Drongo/Photos/Black_Drongo_side.jpg|Male_side,./Media/Black Drongo/Photos/Black_Drongo_Immature.jpg|Immature,', './Media/Black Drongo/Sounds/XC190051 - Black Drongo - Dicrurus macrocercus macrocercus.mp3', ''),
	(65, 70, 'Adult has ashy-grey upperparts, slightly lighter underparts,paler towards belly; red or reddish brown iris; black legs, bill and chin. Juvenile more brown than adult with white edge on underside of tail and brown iris. Sexes similar but male slightly larger. Agile flier executing remarkable twists and turns in air with speed. Mimics calls of other birds. Forages near edge of forests; perches on high open branch to detect prey; swoops down to catch insects on ground or in mid-flight.\r\nHabitat:Forests and more open woodlands in winter.', './Media/Ashy Drongo/Photos/Ashy drongo_back.jpg|Male_back,./Media/Ashy Drongo/Photos/Ashy_Drongo_side.jpg|Male_side,./Media/Ashy Drongo/Photos/Ashy_Drongo_Juvenile.JPG|Juvenile,', './Media/Ashy Drongo/Sounds/XC239393 - Ashy Drongo - Dicrurus leucophaeus leucophaeus.mp3', ''),
	(66, 71, 'Adult has bluish-black upperparts; long deeply forked-tail; greyish-brown throat and breast; white belly and undertail coverts; short legs. Sexes alike. In pairs or small groups of 4 birds,sometimes with other birds. Noisy,makes short flights;often hunts very late in the evenings; sits upright while perched prominently in shrike-like pose.\r\nHabitat: Open forests and well-wooded habitats', './Media/White-bellied Drongo/Photos/White Bellied Drongo.JPG|Male_back,./Media/White-bellied Drongo/Photos/White Bellied Drongo 1.JPG|Male_front,', './Media/White-bellied Drongo/Sounds/XC148772 - White-bellied Drongo - Dicrurus caerulescens caerulescens.mp3', ''),
	(67, 72, 'Stout drongo with thick,squat bill,covered at base by dense rectal feathers. Black plumage glossed bluish-green. Easily confused with Black Drongo, but distinguished by habitat. Short broad tail with shallow fork but widely splayed and up-curved at tip. Immature has white speckled breast,belly,flanks and undertail-coverts. Hawks from perch. Locally common.\r\nHabitat: Dense broad-leaved evergreen and moist deciduous forests.', './Media/Crow-billed Drongo/Photos/Crow-billed drongo_Front.jpg|Male_front,./Media/Crow-billed Drongo/Photos/crow-billed_drongo_back.jpg|Male_back,./Media/Crow-billed Drongo/Photos/Crow-billed_drongo_Juvenile.jpg|Juvenile,', './Media/Crow-billed Drongo/Sounds/XC407833 - Crow-billed Drongo - Dicrurus annectens.mp3', ''),
	(68, 73, 'Medium-sized,glossy black drongo with short crest and long streamers that end in racket-shaped feathers; square-ended rather than forked tail. Juvenile duller with flat-ended tail and no streamers. Sexes alike. Usually in pairs or mixed hunting groups feeding on invertebrates. Sits on perch waiting to swoop on prey; but often fly-catches. Mimics other birds.\r\nNests in trees. \r\nHabitat: Shady lower branches of forests often near streams.', './Media/Lessor racket-tailed Drongo/Photos/Lesser_racket-tailed_Drongo.jpg|Male,./Media/Lessor racket-tailed Drongo/Photos/Lesser_racket-tailed_Drongo_Juvenile.jpg|Juvenile,', './Media/Lessor racket-tailed Drongo/Sounds/XC141813 - Lesser Racket-tailed Drongo - Dicrurus remifer remifer.mp3', ''),
	(69, 74, 'Easily identified by frontal crest,glossy black plumage and long deep forked-tail without rackets. Earlier considered a race of the Greater Racket-tailed Drongo, it is distinguished by longer and more deeply forked-tail, slightly curved up at tip and lack of terminal rackets, shorter crest and more rounded tuft. Also it is found in wetter areas. Vocal mimic,imitating a variety of birds. Sexes alike. Occurs in pairs. Immature has white barring on belly and flanks similar to Greater Racket-tailed.\r\nHabitat: Wet zones forests and nearby hills\r\nRange: Sri Lanka wet zone.', './Media/Sri Lanka Drongo/Photos/Sri-Lanka-Drongo.jpg|Male_front,./Media/Sri Lanka Drongo/Photos/SriLanka_Drongo_side.jpg|Male_side,', './Media/Sri Lanka Drongo/Sounds/XC346188 - Sri Lanka Drongo - Dicrurus lophorinus.mp3', ''),
	(70, 75, 'Small drongo with glossy black plumage and bluish-green purple iridescence. Relatively short,spade-shaped tail with shallow fork,splayed at tips; short and heavy black bill; spiky face feathers give whisker-like appearance. Dark underparts with more gloss over breast. Sexes alike. Perches high on exposed branch,hawking for insects. Very vocal and conspicuous,territorial.Pairs perform noisy displays.\r\nHabitat: Clearings in thick forest usually near streams or water baths.', './Media/Bronzed Drongo/Photos/Bronzed Drongo front.JPG|Male_front,./Media/Bronzed Drongo/Photos/Bronzed Drongo perch.JPG|Male_side_perch,./Media/Bronzed Drongo/Photos/Bronzed Drongo back.jpg|Male_back,./Media/Bronzed Drongo/Photos/Bronzed Drongo closeup.JPG|Male-closeup,', './Media/Bronzed Drongo/Sounds/XC450980 - Bronzed Drongo - Dicrurus aeneus aeneus.mp3', ''),
	(71, 76, 'Glistening blue-black plumage,fine hair-like feathers on forehead; long downward curved pointed beak; diagnostic tail- square-cut,inwardly bent,curling towards outer ends. Sexes alike. Solitary or scattered pairs; strictly arboreal forest bird; small numbers may gather on flowering trees; rather aggressive often seen in mixed hunting parties. Selects exposed branch and flies out to prey.\r\nHabitat: Forests', './Media/Hair-crested Drongo/Photos/Hair-crested drongo.jpg|Male,./Media/Hair-crested Drongo/Photos/Hair-crested Drongo front.jpg|Male_front,./Media/Hair-crested Drongo/Photos/Hair-crested drongo back.jpg|Male_back,', './Media/Hair-crested Drongo/Sounds/XC446940 - Hair-crested Drongo - Dicrurus hottentottus ss samarensis.mp3', ''),
	(72, 77, 'Brownish-black bird with deeply-forked,curved tail. Overall glossy black plumage,except for brownish mantle. Long,heavy; curved black bill.Similar to Black drongo but distinguished by larger bill and brown iridescence to feather and diagnostic curved fork on tail. Slight hair-like whiskers on forehead and beak sides. Sexes similar but female smaller with shallower fork on tail. Often in large groups and sometimes in mixed hunting parties. Feeds on insects often by fly-catching. Nests high in tree fork.\r\n\r\nHabitat: Forests, restricted to Andaman Islands where it is the only common drongo.', './Media/Andaman Drongo/Photos/andaman drongo back.jpg|Male,./Media/Andaman Drongo/Photos/andaman_drongo.jpg|Male_side,./Media/Andaman Drongo/Photos/Andaman_Drongo_in_tree.jpg|Male_back,', './Media/Andaman Drongo/Sounds/XC369179 - Andaman Drongo - Dicrurus andamanensis.mp3', ''),
	(73, 78, 'Glossy blue-black plumage; prominent crest of long feathers,curved face-wards; elongated wire-like outer-tail feathers ending in rackets diagnostic. Distinguished from Lesser racket-tailed by larger size and wider rackets. It is a 32 cm bird with 30 cm streamers. Sexes alike. Solitary or in pairs,sometimes small gatherings; arboreal, but often descends in to lower bushes; moves a lot in forests. Confirmed exhibitionist - both by sight and sound; extremely noisy,often vocal before sunrise; bold and aggressive, seen mobbing bigger birds 100 metres above forest floor.\r\nNoisiest forest bird; amazing mimic, calls include wide variety of whistles and screams, perfect imitations.', './Media/Greater Racket-tailed Drongo/Photos/Greater_Racket_tailed_Drongo.jpg|Male_front,./Media/Greater Racket-tailed Drongo/Photos/Greater_racket-tailed_drongo_crest.jpg|Male_with_big_crest,./Media/Greater Racket-tailed Drongo/Photos/Greater_racket-tailed_drongo.jpg|Male_back,', './Media/Greater Racket-tailed Drongo/Sounds/XC30662 - Greater Racket-tailed Drongo - Dicrurus paradiseus paradiseus.mp3', ''),
	(74, 79, 'Similar to Eurasian Jay,but range restricted to W Himalayas from W Pakistan up to Nepal. Adult has black head with crest,pinkish-buff body,washed grey on rump and mantle. Wings regularly patterned black,blue and white; tail black-barred blue. White streaked throat contrasting with black head;yellow bill. Sexes alike. \r\nHabitat: Mixed temperate forests,particularly oaks, but often in more open areas and human habitation.Less shy than Eurasian', './Media/Black-headed Jay/Photos/Black-headed_Jay_Front.jpg|Male_front,./Media/Black-headed Jay/Photos/Black-headed_Jay_back.jpg|Male_back,./Media/Black-headed Jay/Photos/Black-headed_Jay_Side.jpg|Male_side,', './Media/Black-headed Jay/Sounds/XC351872 - Black-headed Jay - Garrulus lanceolatus.mp3', ''),
	(75, 80, 'Pinkish-brown plumage,velvety-black malar stripe; closely black-barred,blue wings; white crown streaked black; white throat; rufous lesser and median coverts; white rump contrasts with jet-black tail. Sexes alike. Juvenile similar to adult but darker body,grey bill,bluish eyes and brighter legs. In small noisy groups with other birds; good mimic; inquisitive and aggressive; laboured flight.\r\n\r\nHabitat: Mixed temperate forests.', './Media/Eurasian Jay/Photos/Eurasian_Jay.jpg|Male_front,./Media/Eurasian Jay/Photos/Eurasian_Jay_Back.jpg|Male_back,./Media/Eurasian Jay/Photos/Eurasian_Jay_Juvenile.jpg|Juvenile,', './Media/Eurasian Jay/Sounds/XC453963 - Eurasian Jay - Garrulus glandarius.mp3', ''),
	(76, 81, 'Dramatically coloured magpie with deep blue,long tail,chestnut head,breast and lower wings; bright coral red bill, eye ring and legs; white-tipped tail conspicuous in flight. Juvenile duller with brown eye-ring. Usually shy; found in small flocks often with babblers and woodpeckers.\r\nHabitat: Hill forests.', './Media/Sri Lanka Blue Magpie/Photos/SriLanka_Blue_Magpie.jpg|Male,./Media/Sri Lanka Blue Magpie/Photos/SriLanka_Blue_Magpie_front.jpg|Male_front,', './Media/Sri Lanka Blue Magpie/Sounds/XC343022 - Sri Lanka Blue Magpie - Urocissa ornata.mp3', ''),
	(77, 82, 'Purple-blue plumage; black head and breast; white nape patch and underbody; very long white-tipped tail; yellow beak and orange legs. Sexes alike. In pairs or small bands,often associating with jays, laughingtrushes and treepies. wanders a lot in forests,flying across clearings, entering hill station gardens,one bird following another. Arboreal but also hunts in low bushes; even descends to ground long tail cocked as it hops about.\r\nRange: The Himalayas, west to east, 1500-3600 m; may descend low in winter.', './Media/Yellow-billed Blue Magpie/Photos/Yellow-billed_Blue_Magpie_Dugalbitta_Chopta_Uttarakhand_India_13.06.2013.jpg|Male,./Media/Yellow-billed Blue Magpie/Photos/Yellow-billed_blue_magpie_pair.JPG|Pair,./Media/Yellow-billed Blue Magpie/Photos/Yellow-billed_blue_Magpie_in flight.jpg|In Flight,./Media/Yellow-billed Blue Magpie/Photos/Yellow-billed_Blue_Magpie.JPG|Perched,', './Media/Yellow-billed Blue Magpie/Sounds/XC426998 - Yellow-billed Blue Magpie - Urocissa flavirostris.mp3', ''),
	(78, 84, 'Slaty-blue bird with very long tail and robust red bill, black head, neck and breast with bluish spotting on crown. Creamy-grey underparts. Larger than yellow-billed blue magpie and more blue above (purplish in eastern race); larger white nape patch. Black sub-terminal band to white-tipped tail. Red legs. Sexes alike. Juvenile has grey bill,brownish head and back,very similar to Yellow-billed.\r\n\r\nHabitat:Forests, cultivation and gardens at lower altitude than Yellow-billed.', './Media/Red-billed Blue Magpie/Photos/Red-billed_Blue_Magpie.jpg|Male,./Media/Red-billed Blue Magpie/Photos/Red-bille_Blue_Magpie_underside.jpg|Male_side,./Media/Red-billed Blue Magpie/Photos/Red-billed-blue-magpie_Perched.jpg|Perched,', './Media/Red-billed Blue Magpie/Sounds/XC407607 - Red-billed Blue Magpie - Urocissa erythroryncha erythroryncha.mp3', ''),
	(79, 85, 'Large green magpie with vivid red bill. Brilliant emerald green upperparts and paler green underparts. Bold,broad black stripe extending from bill through eyes to a short crest on rear crown.Yellow-green crown,red legs. Wings and chestnut tipped white. Long graduated white-tipped tail. Sexes alike. Feeds low down in foliage or ground in pairs or small groups. Joins mixed hunting groups.\r\nHabitat: Dense broadleaved forests; particularly ravine sides.', './Media/Common Green Magpie/Photos/Common Iora 1.JPG|Male,./Media/Common Green Magpie/Photos/Common_Green_Magpie_side.jpg|Male_side,./Media/Common Green Magpie/Photos/Common_Green_Magpie_back.jpg|Male_back,', '', ''),
	(80, 86, 'Rufous above and below; sooty grey-brown head and neck; black,white and grey on wings, best seen in flight. Long, graduated, black-tipped,grey tail. Sexes alike. In pairs or small parties; feeds up in trees but also descends into bushes and onto ground to pick up termites.\r\n\r\nHabitat: Forests,gardens,cultivation and habitation.', './Media/Rufous Treepie/Photos/Rufous_Treepie_Back.JPG|Male_back,./Media/Rufous Treepie/Photos/Rufous_Treepie_1.JPG|Male_front,', './Media/Rufous Treepie/Sounds/XC201924 - Rufous Treepie - Dendrocitta vagabunda.mp3,./Media/Rufous Treepie/Sounds/XC425927 - Rufous Treepie - Dendrocitta vagabunda.mp3,', ''),
	(81, 87, 'Duller and less rufous than Rufous Treepie; grey-brown plumage; dusky grey face and grey head,neck and underparts. Rufous vent; long, graduated grey tail, black-edged and tipped; brownish back and black wings with white-patch. Sexes alike. Less often near human habitation than Rufous Treepie. Behaviour and food as Rufous but shyer. Arboreal, often in groups or mixed hunting parties. Seems to keep company of drongos.\r\nHabitat: Forests, secondary growth.', './Media/Grey Treepie/Photos/Grey_Treepie_front.jpg|Male_front,./Media/Grey Treepie/Photos/Grey_Treepie.jpg|Male_side,./Media/Grey Treepie/Photos/Grey_Treepie-perched.jpg|Male_perched,', './Media/Grey Treepie/Sounds/XC448004 - Grey Treepie - Dendrocitta formosae.mp3,./Media/Grey Treepie/Sounds/XC449732 - Grey Treepie - Dendrocitta formosae.mp3,', ''),
	(82, 88, 'White,grey and chestnut crow with very long,black-tipped and pale grey-edged tail. Black face contrasts with white head and underparts. Chestnut mantle and black wings with white-patches. Sexes alike. Sociable, often with Greater Racket-tailed Drongos whom they imitate freely as well as other forest species. Feeds mainly invertebrates at lower and middle branches. Nests in shrubs.\r\nHabitat: Evergreen hill forests; thick scrub and plantations.\r\nRange: Local breeding endemic resident in South Western Ghats.', './Media/White-bellied Treepie/Photos/White-bellied-treepie_front.jpg|Male_front,./Media/White-bellied Treepie/Photos/White-bellied Treepie_back.jpg|Male_back,./Media/White-bellied Treepie/Photos/White-bellied Treepie.JPG|Male_perched,', './Media/White-bellied Treepie/Sounds/XC100752 - White-bellied Treepie - Dendrocitta leucogastra.mp3,./Media/White-bellied Treepie/Sounds/XC416748 - White-bellied Treepie - Dendrocitta leucogastra.mp3,', ''),
	(83, 89, '\r\n\r\n\r\nIts range overlaps with Grey and Rufous Treepies; patchy distribution in extreme E Nepal, Bhutan and Arunachal Pradesh.\r\nSmaller treepie with compact body and long black tail. Black face and throat with pale grey head, nape,breast and upper belly. Rufous mantle, lower belly, rump and vent; long black tail(not grey). Black wings with grey panels on coverts, no white-patch. In flight black tail, rufous vent and rump distinguish it from Rufuos Treepie. Singly or in small groups; joins mixed hunting parties; mainly arboreal; not as noisy as Rufous or Grey Treepie.\r\n\r\nHabitat: Thick,tropical, sub-tropical, temperate evergreen,semi-evergreen forests; bamboos', './Media/Collared Treepie/Photos/Collared_Treepie.jpg|Male_front,./Media/Collared Treepie/Photos/Collared_treepie-perched.jpg|Male_back,./Media/Collared Treepie/Photos/Collared_trrepie_In_Flight.jpg|Male_in_flight,', './Media/Collared Treepie/Sounds/XC19251 - Collared Treepie - Dendrocitta frontalis.mp3,./Media/Collared Treepie/Sounds/XC170494 - Collared Treepie - Dendrocitta frontalis.mp3,', ''),
	(84, 90, 'Long-tailed dark crow with startling yellow iris; black face,wings and tail; dark grey head and neck; deep brown back; chestnut underparts and white wing-patches. Smaller than other treepies. Sexes alike. Behaviour as other treepies and seems to seek company of Andaman Drongos.\r\nHabitat: Subtropical or tropical moist lowland forests.\r\nRange: Fairly common breeding endemic resident of the Andaman Islands.', './Media/Andaman Treepie/Photos/Andaman_treepie_side.jpg|Male_side,./Media/Andaman Treepie/Photos/Andaman_treepie_front.jpg|Male_front,./Media/Andaman Treepie/Photos/Andaman_treepie_back.jpg|Male_back,', './Media/Andaman Treepie/Sounds/XC369144 - Andaman Treepie - Dendrocitta bayleii.mp3', ''),
	(85, 91, 'Pied bird with glossy black head,neck,upper back and wings; tail glossed bronze-green and purple-blue; white scapulars rump and belly; black undertail. Sexes alike. Tibetan race(bottanensis) can be identified by black rump. Usually, several in vicinity; moves on ground, perches on fence posts, trees, house-tops; frequents high-mountain villages; typical crow - bold and aggressive, but also extremely alert; flicks tail often.\r\nRange: High NW Himalayas,Chitral,N Kashmir, Ladakh,Himachal Pradesh; Tibetan race found in Bhutan and Arunachal, 1500 -4700 m.', './Media/Eurasian Magpie/Photos/Eurasian_Magpie.JPG|Male_on_ground,./Media/Eurasian Magpie/Photos/Eurasian_Magpie_side.jpg|Male_side,./Media/Eurasian Magpie/Photos/Eurasian_Magpie_in_flight.jpg|Male_in_flight,', './Media/Eurasian Magpie/Sounds/XC452123 - Eurasian Magpie - Pica pica.mp3', ''),
	(86, 92, 'Chocolate-brown plumage,thickly speckled with white;dark central tail feathers,tipped white; white outer tail and undertail coverts; heavy pointed beak distinctive. Sexes alike. The race hemispila, found between Kangra and CE Nepal has smaller white spots; spots absent on rump. small parties in temperate forests; keeps to tree-tops but readily descends onto ground; rather wary; flies short distances across glades; rather noisy, usually calling to attract attention.\r\nHabitat: Coniferous,oak,rhododendron forests.\r\nRange: The Himalayas 1800-4000m sometimes descending to about 1200m in winter.', './Media/Spotted Nutcracker/Photos/Large_Spotted_Nutcracker-Kashmir-Nutcracker.jpg|Large_Spotted_Nutcracker,./Media/Spotted Nutcracker/Photos/Spotted_nutcracker.JPG|Spotted_Nutcracker,./Media/Spotted Nutcracker/Photos/Spotted_nutcracker_in flight.jpg|Spotted_Nutcracker_in_Flight,', './Media/Spotted Nutcracker/Sounds/XC177029 - Spotted Nutcracker - Nucifraga caryocatactes macella.mp3', ''),
	(87, 93, 'Gregarious, noisy forest-dwelling bird with vivid plumage. Long,thin,blue tail; black head; yellow face and throat sides; blue-patch on crown; yellow ear-covert patch; yellow-green bill; large eyes; bright green upperparts; blue-green underparts. Diagnostic white-patch on blue underwing,visible in flight. Juvenile duller,mostly green. Arboreal and crepuscular;feeds on insects. Perches upright.\r\nHabitat: Tropical,sub-tropical semi-evergreen,evergreen forests; bamboos, sal.', './Media/Long-tailed Broadbill/Photos/Long-tailed Broadbill front.jpg|Male_front,./Media/Long-tailed Broadbill/Photos/Long-tailed broadbill.jpg|Male_back,', './Media/Long-tailed Broadbill/Sounds/XC409496 - Long-tailed Broadbill - Psarisomus dalhousiae psittacinus.mp3', ''),
	(88, 94, 'Adult male has red lores; rusty head sides and ear-coverts; grey forehead; broad black eyebrow continuing through to neck; yellow eye-ring. Black wings with blue-and-white wing patches; ash-brown mantle;chestnut lower back; brown rump; black tail with white border. Silvery grey throat and chest graduating to white belly;black thighs. Iris varies from emerald-green to sapphire-blue. Female identified by thin silver band running through upper chest.\r\nHabitat: Lowlands, foothill forests.\r\nRange: Scarce breeding resident, now restricted to extreme NE India along Myanmar border.', './Media/Silver-breasted Broadbill/Photos/Silver-breasted_Broadbill.jpg|Male,./Media/Silver-breasted Broadbill/Photos/Silver-breasted_broadbill_female.jpg|Female,./Media/Silver-breasted Broadbill/Photos/Silver-breasted_broadbill_female_front.jpg|Female_front,', './Media/Silver-breasted Broadbill/Sounds/XC396711 - Silver-breasted Broadbill - Serilophus lunatus lunatus.mp3', ''),
	(89, 95, 'Olive green pitta with striking blue hind-crown and nape. Fulvous head-sides,forehead and ear-coverts; black patch behind eye. Plain, uniform fulvous underparts; brownish-green wings; brown tail washed green. Brown iris and bill. Female is smaller and has rufous-brown crown,greenish-blue patch on nape. Forages on forest floor amidst fallen leaves.\r\nHabitat: Tropical and sub-tropical moist broad-leaved evergreen forests; bamboo-dominated secondary growth in deserted forest clearings.', './Media/Blue-naped Pitta/Photos/Blue-naped Pitta_male.png|Male,./Media/Blue-naped Pitta/Photos/Blue-naped_pitta_male_back.jpg|Male_back,./Media/Blue-naped Pitta/Photos/Blue-naped Pitta female.jpg|Female,', './Media/Blue-naped Pitta/Sounds/XC426632 - Blue-naped Pitta - Hydrornis nipalensis.mp3', ''),
	(90, 96, 'Medium-sized, distinctly azure blue pitta. Pinkish-red hindcrown; broad black eye-stripe and moustachial stripe. Bright blue tail. Pale underparts tinted blue with bold black spotted and barring. Small white-patch in wing visible in flight. Female has dark olive upperparts with variable blue tinge; buff breast. Juvenile overall dark brown, streaked and spotted rufous-buff; prominent buff supercilium and da rk eye stripe.\r\nHabitat: Broad-leaved evergreen forests; moist ravines\r\nRange: Rare Resident, NE India and Bangladesh.', './Media/Blue Pitta/Photos/Blue_Pitta_male_front.jpg|Male_front,./Media/Blue Pitta/Photos/Blue_Pitta_male.jpg|Male_side,./Media/Blue Pitta/Photos/Blue_Pitta_female.jpg|Female,', './Media/Blue Pitta/Sounds/XC406607 - Blue Pitta - Hydrornis cyaneus.mp3', ''),
	(91, 97, 'Unmistakably bright emerald-green pitta with black face and rusty-brown forehead, crown and nape; blue rump and shoulders; part of rump bright red; brown iris; black bill; strong and long flesh-colored legs. Paler green underparts; short tail. Large white-patches on dark wings prominent in flight. Feeds on invertebrates on wet forest floor with bounding hops. Calls and roosts on trees. Solitary and secretive. Nests low down.\r\nHabitat: Forest undergrowth and thick scrub, favours dark, damp, leaf-strewn areas.\r\nRange: Rare and very local breeding summer visitor to N foothills from Himachal to Myanmar border including Nepal and Bangladesh.', './Media/Hooded Pitta/Photos/Hooded_Pitta.jpg|Male,./Media/Hooded Pitta/Photos/Hooded_Pitta_front.jpg|Male_front,./Media/Hooded Pitta/Photos/Hooded pitta side.jpg|Male_side,', './Media/Hooded Pitta/Sounds/XC409825 - Hooded Pitta - Pitta sordida rosenbergii.mp3', ''),
	(92, 98, 'Multicoloured, stub-tailed, stoutly built bird; bright blue, green, black, white, yellowish-brown and crimson; white chin, throat and patch on wings-tips and crimson vent. Sexes alike. Solitary or pairs; spends much time on ground, hopping about, hunting for insects amidst leaf litter and low herbage; quietly flies into tree branch if disturbed, fond of shaded and semi-damp areas.\r\nHabitat: Forests, orchards and cultivate country.', './Media/Indian Pitta/Photos/Indian_Pitta.jpg|Male,./Media/Indian Pitta/Photos/Indian_Pitta_front.jpg|Male_front,./Media/Indian Pitta/Photos/Indian_Pitta_side.jpg|Male_side,', './Media/Indian Pitta/Sounds/XC453370 - Indian Pitta - Pitta brachyura.mp3', ''),
	(93, 99, 'Closely resembles Indian Pitta with typical black stripe around eye. White throat; buff breast and flanks; red belly. However has longer, heavier beak and dark brown crown without the characteristic black coronal stripe. Also larger, white wing patch and distinctively different call. Usually seen hopping in exposed mud among mangrove roots and adjacent drier land vegetation. Builds dome-shaped nest of twigs and leaves on banks or in vegetation close to ground, near high-tide line.\r\nHabitat: Mangroves\r\nRange: Probably very local resident in the Sunderbans and Odisha coasts.', './Media/Mangrove Pitta/Photos/Mangrove_Pitta.jpg|Male,./Media/Mangrove Pitta/Photos/Mangrove_Pitta_side.jpg|Male_side,./Media/Mangrove Pitta/Photos/Mangrove_Pitta_back.jpg|Male_back,', './Media/Mangrove Pitta/Sounds/XC447844 - Mangrove Pitta - Pitta megarhyncha.mp3', ''),
	(94, 100, 'Plain, thickset, shrike-like bird with drab plumage; heavy, black bill; distinct nasal tufts. It has grey crown and nape; brown mantle and upperparts; fairly broad, dark mask; black bill; usually yellow eyes; breast, flanks have pale pink-grey wash. Female duller with brown upperparts and ill-defined mask; paler bill. Juvenile has spotted, scaly crown. Fairly confiding but quiet and inconspicuous.\r\nHabitat: Moist evergreen, broadleaved forests; glades.\r\nRange: Lowlands; E Nepal.', './Media/Large Woodshrike/Photos/Large_woodshrike_male_back.jpg|Male,./Media/Large Woodshrike/Photos/Large_Woodshrike_female.jpg|Female,./Media/Large Woodshrike/Photos/Large_Woodshrike - Juvenile.jpg|Juvenile,', './Media/Large Woodshrike/Sounds/XC149783 - Large Woodshrike - Tephrodornis virgatus pelvicus.mp3', ''),
	(95, 101, 'Grey-brown plumage; broad whitish supercilium and dark stripe below eye distinctive; grey-brown lores; white outer tail feathers seen when bird flies. Sexes alike. Dark stripe may be slightly paler in female. In pairs, or small parties; quiet for greater part of the year, vocal when breeding (Feb-May). Keeps to middle levels of trees, hopping about, sometimes coming to ground. Nest in a small cup of bark held by cobwebs and lichen. It is lined by silky plant fibers.\r\nHabitat: Light forests, edges of forests, cultivation, gardens in and around habitation.', './Media/Common Woodshrike/Photos/Common Woodshrike.jpg|Male,./Media/Common Woodshrike/Photos/Common Woodshrike_side.jpg|Male_side,./Media/Common Woodshrike/Photos/Common Woodshrike_female.jpg|Female,', './Media/Common Woodshrike/Sounds/XC348715 - Common Woodshrike - Tephrodornis pondicerianus Urocissa erythroryncha.mp3', ''),
	(96, 102, 'Recently separated from Large woodshrike, differentiated by more slaty-grey crown,nape and mantle; pinkish-grey throat and breast; well-defined, white sub-moustachial stripe. Female similar to male but has darker brown on upperparts and less-defined mask.\r\nHabitat: Broadleaved forests and well-wooded areas.\r\nRange: SE Gujarat and S Western Ghats.', './Media/Malabar Woodshrike/Photos/Malabar woodshrike -Male-front.jpg|Male_front,./Media/Malabar Woodshrike/Photos/Malabar woodshrike -Male.jpg|Male_back,./Media/Malabar Woodshrike/Photos/Malabar woodshrike -Female.jpg|Female,', './Media/Malabar Woodshrike/Sounds/XC134748 - Malabar Woodshrike - Tephrodornis sylvicola.mp3', ''),
	(97, 103, 'Slaty-grey plumage, grey on head; paler on rump and underbody; short square tail,tipped white; white undertail coverts; bluish bill; black lores; heavy-looking bird, swallow-like in appearance but wings shorter and broader. Sexes alike. Small numbers in open country; perches on leaf-stalks,overhead wires. Characteristic flight- few wingbeats then glides; hunts flying insects; quiet during hot hours, feeds mostly in mornings and evenings.\r\n', './Media/Ashy Woodswallow/Photos/Ashy Woodswallow.jpg|Male,./Media/Ashy Woodswallow/Photos/Ashy Woodswallow side.jpg|Male_side,./Media/Ashy Woodswallow/Photos/Ashy Woodswallow back.jpg|Male_back,', './Media/Ashy Woodswallow/Sounds/XC446304 - Ashy Woodswallow - Artamus fuscus.mp3', ''),
	(98, 104, 'Small woodswallow with large head and relatively short,broad tail. Dark grey upperparts, hood and throat; white rump and uppertail-coverts. Creamy-white underparts; blackish primaries; flight feathers and tail narrowly-tipped white. Dark brown iris, bluish-grey legs. Sexes alike. Juvenile similar to adult but darker brown.\r\n\r\nHabitat:Often seen tightly bunched together in large flocks on power lines and branches in forest clearings\r\nRange: Common breeding, resident in Andaman Islands.', './Media/White-breasted Woodswallow/Photos/White-breasted Woodswallow_back.jpg|Male_back,./Media/White-breasted Woodswallow/Photos/White-breasted Woodswallow_single.jpg|Male,./Media/White-breasted Woodswallow/Photos/White-breasted Woodswallows Flock.jpg|Flock,', './Media/White-breasted Woodswallow/Sounds/XC410189 - White-breasted Woodswallow - Artamus leucorynchus.mp3', ''),
	(99, 106, 'Largest francolin with unusually long legs. Brown crown, beige supercilium and thin brown eye stripe that extend to neck. Upper throat and upper neck rusty-brown. Back and wings have a mix of black and brown feathers with whites flashes on the chest. Chestnut flight feathers and outer tail. Underparts brown and longitudinally streaked white. Black bill and dull pale red legs. Sexes alike, but female smaller and lacks spurs. Male has darker legs. Shy, seen in pairs or small groups near rivers and jheel edges in tall wet grasslands. Comes in to open ground or cultivation to feed. Nests on a pad in shallow water amongst reeds.\r\n\r\nRange: Globally threatened; breeding endemic resident restricted to Nepal, N India and Assam.\r\nHabitat: Tall grasslands; swamp and sugarcane fields.', './Media/Swamp Francolin/Photos/Swamp_francolin_male_crowing.jpg|Male,./Media/Swamp Francolin/Photos/Swamp_francolin_male_side.jpg|Male_side,', './Media/Swamp Francolin/Sounds/XC35558 - Swamp Francolin - Francolinus gularis.mp3', ''),
	(100, 108, 'Medium-sized, vivid leaf-green bird. Male has golden-orange forehead; bluish-black chin and cheeks; black lores; orangish ear-coverts, continuing as loop around blue throat. Glossy blue flash on shoulder. Female duller. Black chin and throat absent in juvenile; green crown Usually in pairs, favors canopy. Hunts actively; rather aggressive and territorial.\r\n\r\nHabitat: Forests.', './Media/Golden-fronted Leafbird/Photos/Golden-fronted leafbird male_front.JPG|Male,./Media/Golden-fronted Leafbird/Photos/Golden-fronted_Leafbird_perched.JPG|Male-birdbath,./Media/Golden-fronted Leafbird/Photos/Golden-fronted_Leafbird.JPG|Male_back,', './Media/Golden-fronted Leafbird/Sounds/XC423283 - Golden-fronted Leafbird - Chloropsis aurifrons.mp3', ''),
	(101, 111, 'Distinguished easily from Golden-fronted leafbird by lack of golden orange crown. Male has black throat that continues to lower eyelid; black cheeks; blue mustache; greenish-yellow forehead. Bluish-green lesser wing coverts; underparts softer green. Female has greenish-blue throat and cheeks; blue moustache. Juvenile uniform leaf green. Prefers canopy, well camouflaged in foliage.\r\n\r\nHabitat: Edge of forests, groves, open forests, gardens, isolated large trees near villages or in cultivation.', './Media/Jerdon\'s Leafbird/Photos/Jerdon\'s_Leafbird.jpg|Male,./Media/Jerdon\'s Leafbird/Photos/Jerdon\'s_Leafbird_female.jpg|Female,', './Media/Jerdon\'s Leafbird/Sounds/XC454351 - Jerdon\'s Leafbird - Chloropsis jerdoni.mp3', ''),
	(102, 112, 'Male overall bright green with lighter green head. Turquoise-blue edges to primary coverts and primaries(duller on female and juvenile);blue sides to tail, diagnostic. Black face and throat; blue moustachial stripe. Uniform, green underparts. Strong black beak with bristles at base. Female greener on head; has turquoise-blue throat patch. Juvenile like female but no blue on throat.\r\n\r\nHabitat: Edges of forests, groves, open forests, gardens, isolated large trees near villages or in cultivation.', './Media/Blue-winged Leafbird/Photos/Blue-winged_leafbird_Male_back.jpg|Male_back,./Media/Blue-winged Leafbird/Photos/Blue-winged_leafbird_Male_front.jpg|Male_front,./Media/Blue-winged Leafbird/Photos/Blue-winged_leafbird_female.jpg|Female,./Media/Blue-winged Leafbird/Photos/Blue-winged_leafbird_juvenile.jpg|Juvenile,', './Media/Blue-winged Leafbird/Sounds/XC424687 - Blue-winged Leafbird - Chloropsis cochinchinensis viridinucha.mp3', ''),
	(103, 113, 'Dramatically-colored leafbird with bright orange lower breast and belly. Bright leaf-green back; yellowish-green forehead, crown and nape; broad iridescent blue moustachial band; blue patch over throat and chest; blue edges to outer-wing coverts, primaries, tail sides; blue shoulder patches. Female greener; less extensive orange on undersides. Solitary, in pairs or mixed parties; arboreal; usually in canopy or upper branches.\r\n\r\nHabitat: Broad-leaved evergreen, deciduous forests, secondary growth.', './Media/Orange-bellied Leafbird/Photos/Orange-bellied_Leafbird_male.jpg|Male,./Media/Orange-bellied Leafbird/Photos/Orange-bellied_Leafbird_noshine.jpg|Male_no_iridescence,./Media/Orange-bellied Leafbird/Photos/Orange-bellied_Leafbird_female.jpg|Female,', './Media/Orange-bellied Leafbird/Sounds/XC449728 - Orange-bellied Leafbird - Chloropsis hardwickii.mp3', ''),
	(104, 114, 'Similar to Common Iora, but white edgings to tertials diagnostic; smaller and shorter bill. Breeding male has black crown and nape. Non-breeding male has greenish-yellow upperparts. Female identical to non-breeding male.\r\n\r\nHabitat: Open woodlands and thorn scrub, often drier habitats than Common Iora.\r\n\r\nRange: Now, rare and declining endemic breeding resident confined to NW India.', './Media/Marshall\'s Iora/Photos/Marshall\'s Iora_Br_Male.jpg|Male_breeding,./Media/Marshall\'s Iora/Photos/Marshall\'s iora -female.jpg|Female,', './Media/Marshall\'s Iora/Sounds/XC211909 - Marshalls Iora - Aegithina nigrolutea.mp3', '');
/*!40000 ALTER TABLE `x_birddescription` ENABLE KEYS */;


-- Dumping structure for table birds.x_birdplumage
CREATE TABLE IF NOT EXISTS `x_birdplumage` (
  `bitPosition` smallint(5) unsigned NOT NULL,
  `Colour` varchar(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table birds.x_birdplumage: ~9 rows (approximately)
/*!40000 ALTER TABLE `x_birdplumage` DISABLE KEYS */;
INSERT INTO `x_birdplumage` (`bitPosition`, `Colour`) VALUES
	(1, 'BLACK'),
	(2, 'GREY'),
	(4, 'WHITE'),
	(8, 'BUFF/BROWN'),
	(16, 'RED/RUFOUS'),
	(32, 'YELLOW'),
	(64, 'OLIVE/GREEN'),
	(128, 'BLUE'),
	(256, 'ORANGE');
/*!40000 ALTER TABLE `x_birdplumage` ENABLE KEYS */;


-- Dumping structure for table birds.x_birds
CREATE TABLE IF NOT EXISTS `x_birds` (
  `birdId` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `CommonName` varchar(128) NOT NULL,
  `ScientificName` varchar(128) NOT NULL,
  `Classification` varchar(128) NOT NULL,
  `Behaviour` tinyint(4) NOT NULL,
  `Plumage` smallint(5) unsigned NOT NULL,
  `Size` smallint(6) NOT NULL,
  PRIMARY KEY (`birdId`)
) ENGINE=InnoDB AUTO_INCREMENT=115 DEFAULT CHARSET=latin1;

-- Dumping data for table birds.x_birds: ~96 rows (approximately)
/*!40000 ALTER TABLE `x_birds` DISABLE KEYS */;
INSERT INTO `x_birds` (`birdId`, `CommonName`, `ScientificName`, `Classification`, `Behaviour`, `Plumage`, `Size`) VALUES
	(3, 'Snow Partridge', 'Lerwa lerwa', 'Pheasants and partridges', 4, 21, 38),
	(4, 'Tibetan Snowcock', 'Tetraogallus tibetanus', 'Pheasants and partridges', 4, 23, 51),
	(5, 'Himalyan Snowcock', 'Tetraogallus himalayensis', 'Pheasants and partridges', 4, 54, 72),
	(6, 'Chukar Partridge', 'Alectoris chukar', 'Pheasants and partridges', 4, 31, 38),
	(7, 'Black  Francolin', 'Francolinus francolinus', 'Pheasants and partridges', 6, 29, 34),
	(8, 'Painted Francolin', 'Francolinus pictus', 'Pheasants and partridges', 12, 29, 31),
	(9, 'Gray Francolin', 'Frankolinus pondicerianus', 'Pheasants and partridges', 4, 267, 34),
	(10, 'Red Avadavat', 'Amandava amandava', 'Avadavats and Munias', 5, 31, 10),
	(11, 'Indian Silverbill', 'Euodice malabarica', 'Avadavats and Munias', 5, 15, 10),
	(12, 'Scaly Breasted Munia', 'Lonchura punctulata', 'Avadavats and Munias', 13, 300, 10),
	(13, 'White Rumped Munia', 'Lonchura striata', 'Avadavats and Munias', 28, 13, 10),
	(14, 'Green Avadavat', 'Amandava formosa', 'Avadavats and Munias', 8, 101, 10),
	(15, 'Black throated Munia', 'Lonchura kelaarti', 'Avadavats and Munias', 12, 13, 12),
	(16, 'Black headed Munia', 'Lonchura malacca', 'Avadavats and Munias', 12, 21, 10),
	(17, 'Chestnut Munia', 'Lonchura m atricapilla', 'Avadavats and Munias', 12, 13, 10),
	(18, 'Large Cuckooshrike', 'Coracina macei', 'Cuckooshrikes', 8, 7, 28),
	(19, 'Bar-belied Cuckooshrike', 'Coracina striata', 'Cuckooshrikes', 8, 22, 26),
	(20, 'Black-winged Cuckooshrike', 'Coracina melaschistos', 'Cuckooshrikes', 8, 7, 22),
	(21, 'Black-headed Cuckooshrike', 'Coracina melanoptera', 'Cuckooshrikes', 8, 15, 20),
	(22, 'Pied Triller', 'Lalage nigra', 'Cuckooshrikes', 8, 7, 18),
	(23, 'Common Iora', 'Aegithina tiphia', 'Iora', 9, 101, 14),
	(24, 'Alexandrine Parakeet', 'Psittacula eupatria', 'Parrots and allies', 13, 113, 53),
	(25, 'Rose-ringed parakeet', 'Psittacula krameri', 'Parrots and allies', 13, 81, 42),
	(26, 'Bar-bellied Cuckooshrike', 'Psittacula himalayana', 'Parrots and allies', 44, 497, 40),
	(27, 'Grey-headed Parakeet', 'Psittacula finschii', 'Parrots and allies', 9, 499, 33),
	(28, 'Plum-headed Parakeet', 'Psittacula cyanocephala', 'Parrots and allies', 12, 119, 36),
	(29, 'Blossom-headed Parakeet', 'Psittacula roseata', 'Parrots and allies', 8, 243, 36),
	(30, 'Malabar Parakeet', 'Psittacula columboides', 'Parrots and allies', 8, 243, 38),
	(31, 'Layard\'s Parakeet', 'Psittacula calthropae', 'Parrots and allies', 9, 243, 31),
	(32, 'Derbyan Parakeet', 'Psittacula derbiana', 'Parrots and allies', 8, 211, 46),
	(33, 'Nicobar Parakeet', 'Psittacula caniceps', 'Parrots and allies', 8, 83, 61),
	(34, 'Long-tailed Parakeet', 'Psittacula longicauda', 'Parrots and allies', 12, 113, 47),
	(35, 'Red-breasted Parakeet', 'Psittacula alexandri', 'Parrots and allies', 8, 243, 38),
	(36, 'Vernal Hanging Parrot', 'Loriculus vernalis', 'Parrots and allies', 8, 478, 15),
	(37, 'Sri Lanka Hanging Parrot', 'Loriculus beryllinus', 'Parrots and allies', 8, 470, 14),
	(38, 'Oriental Turtle Dove', 'Streptopelia Orientalis', 'Pigeons and doves', 28, 31, 32),
	(40, 'Red Collared Dove', 'Streptopelia tranquebarica', 'Pigeons and doves', 28, 31, 23),
	(41, 'Spotted Dove', 'Stigmatopelia chinensis', 'Pigeons and doves', 21, 15, 30),
	(42, 'Laughing Dove', 'Stigmapelia senegalensis', 'Pigeons and doves', 21, 15, 27),
	(43, 'Emerald Dove', 'Chalcophaps indica', 'Pigeons and doves', 12, 94, 26),
	(44, 'Barred Cuckoo Dove', 'Macropygia unchall', 'Pigeons and doves', 40, 90, 41),
	(45, 'Andaman Cuckoo Dove', 'Macropygia rufipennis', 'Pigeons and doves', 8, 26, 41),
	(46, 'Yellow-bellied Fantail', 'Chelidorhynx hypoxantha', 'Fantails', 8, 103, 13),
	(47, 'White-throated Fantail', 'Rhipidura albicollis', 'Fantails', 8, 15, 17),
	(48, 'White-browed fantail', 'Rhipidura aureola', 'Fantails', 8, 13, 17),
	(51, 'Spot-breasted Fantail', 'Rhipidura albogularis', 'Fantails', 8, 15, 19),
	(52, 'Nicobar Megapode', 'Megapodius nicobariensis', 'Megapodes', 12, 24, 43),
	(53, 'Eurasian Collared Dove', 'Streptopelia decaocto', 'Pigeons and doves', 28, 15, 32),
	(54, 'Black-naped Monarch', 'Hypothymis azurea', 'Monarch Flycatchers', 8, 135, 16),
	(63, 'Indian Paradise Flycatcher', 'Terpsiphone paradisi', 'Monarch Flycatchers', 8, 151, 50),
	(64, 'Golden Oriole', 'Oriolus kundoo', 'Old World Orioles', 9, 125, 25),
	(65, 'Slender-billed Oriole', 'Oriolus tenuirostris', 'Old World Orioles', 8, 113, 27),
	(66, 'Black-naped Oriole', 'Oriolus chinensis', 'Old World Orioles', 8, 113, 25),
	(67, 'Black-hooded Oriole', 'Oriolus xanthornus', 'Old World Orioles', 9, 49, 25),
	(68, 'Maroon Oriole', 'Oriolus trailli', 'Old World Orioles', 8, 31, 28),
	(69, 'Black Drongo', 'Dicrurus macrocercus', 'Drongos', 29, 5, 31),
	(70, 'Ashy Drongo', 'Dicrurus leucophaeus', 'Drongos', 12, 31, 30),
	(71, 'White-bellied Drongo', 'Dicrurus caerulescens', 'Drongos', 8, 143, 24),
	(72, 'Crow-billed Drongo', 'Dicrurus annectans', 'Drongos', 8, 133, 28),
	(73, 'Lessor racket-tailed Drongo', 'Dicrurus remifer', 'Drongos', 8, 11, 25),
	(74, 'Sri Lanka Drongo', 'Dicrurus p lophorinus', 'Drongos', 8, 5, 33),
	(75, 'Bronzed Drongo', 'Dicrurus aeneus', 'Drongos', 8, 1, 24),
	(76, 'Hair-crested Drongo', 'Dicrurus hottentottus', 'Drongos', 8, 129, 32),
	(77, 'Andaman Drongo', 'Dicrurus andamanensis', 'Drongos', 8, 9, 35),
	(78, 'Greater Racket-tailed Drongo', 'Dicrurus paradiseus', 'Drongos', 8, 129, 62),
	(79, 'Black-headed Jay', 'Garrulus lanceolatus', 'Crows,jays,ravens,magpies', 25, 143, 33),
	(80, 'Eurasian Jay', 'Garrulus glandarius', 'Crows,jays,ravens,magpies', 12, 143, 33),
	(81, 'Sri Lanka Blue Magpie', 'Urocissa ornata', 'Crows,jays,ravens,magpies', 8, 157, 47),
	(82, 'Yellow-billed Blue Magpie', 'Urocissa flavirostris', 'Crows,jays,ravens,magpies', 13, 421, 66),
	(84, 'Red-billed Blue Magpie', 'Urocissa erythrorhyncha', 'Crows,jays,ravens,magpies', 13, 159, 70),
	(85, 'Common Green Magpie', 'Cissa chinensis', 'Crows,jays,ravens,magpies', 12, 125, 47),
	(86, 'Rufous Treepie', 'Dendrocitta vagbunda', 'Crows,jays,ravens,magpies', 13, 31, 50),
	(87, 'Grey Treepie', 'Dendrocitta formosae', 'Crows,jays,ravens,magpies', 9, 31, 40),
	(88, 'White-bellied Treepie', 'Dendrocitta leucogastra', 'Crows,jays,ravens,magpies', 8, 15, 50),
	(89, 'Collared Treepie', 'Dendrocitta frontalis', 'Crows,jays,ravens,magpies', 8, 23, 38),
	(90, 'Andaman Treepie', 'Dendrocitta bayleyii', 'Crows,jays,ravens,magpies', 13, 47, 36),
	(91, 'Eurasian Magpie', 'Pica pica', 'Crows,jays,ravens,magpies', 29, 197, 52),
	(92, 'Spotted Nutcracker', 'Nucifraga caryocatactes', 'Crows,jays,ravens,magpies', 44, 13, 35),
	(93, 'Long-tailed Broadbill', 'Psarisomus dalhousiae', 'Broadbills', 8, 229, 28),
	(94, 'Silver-breasted Broadbill', 'Serilophus lunatus', 'Broadbills', 8, 511, 19),
	(95, 'Blue-naped Pitta', 'Pitta nipalnesis', 'Pittas', 12, 249, 25),
	(96, 'Blue Pitta', 'Pitta cyanea', 'Pittas', 12, 189, 23),
	(97, 'Hooded Pitta', 'Pitta sordida', 'Pittas', 12, 221, 19),
	(98, 'Indian Pitta', 'Pitta brachyura', 'Pittas', 12, 253, 19),
	(99, 'Mangrove Pitta', 'Pitta megarhyncha', 'Pittas', 6, 253, 20),
	(100, 'Large Woodshrike', 'Tephrodornis virgatus', 'Woodshrikes', 8, 43, 23),
	(101, 'Common Woodshrike', 'Tephrodornis pondicerianus', 'Woodshrikes', 13, 15, 16),
	(102, 'Malabar Woodshrike', 'Tephrodornis v sylvicola', 'Woodshrikes', 8, 47, 23),
	(103, 'Ashy Woodswallow', 'Artamus fuscus', 'Woodswallows', 48, 135, 19),
	(104, 'White-breasted Woodswallow', 'Artamus leucorynchus', 'Woodswallows', 56, 143, 18),
	(106, 'Swamp Francolin', 'Francolinus gularis', 'Pheasants and partridges', 6, 29, 37),
	(108, 'Golden-fronted Leafbird', 'Chloropsis aurifrons', 'Leafbirds', 8, 481, 19),
	(111, 'Jerdon\'s Leafbird', 'Chloropsis jerdoni', 'Leafbirds', 8, 225, 20),
	(112, 'Blue-winged Leafbird', 'Chloropsis cochinchinensis', 'Leafbirds', 8, 225, 20),
	(113, 'Orange-bellied Leafbird', 'Chloropsis hardwickii', 'Leafbirds', 8, 481, 20),
	(114, 'Marshall\'s Iora', 'Aegithina nigrolutea', 'Ioras', 8, 101, 14);
/*!40000 ALTER TABLE `x_birds` ENABLE KEYS */;


-- Dumping structure for table birds.x_birdsizes
CREATE TABLE IF NOT EXISTS `x_birdsizes` (
  `sizeId` tinyint(3) unsigned NOT NULL,
  `lowerLimit` tinyint(3) unsigned NOT NULL,
  `upperLimit` tinyint(3) unsigned NOT NULL,
  `comparableBird` varchar(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table birds.x_birdsizes: ~7 rows (approximately)
/*!40000 ALTER TABLE `x_birdsizes` DISABLE KEYS */;
INSERT INTO `x_birdsizes` (`sizeId`, `lowerLimit`, `upperLimit`, `comparableBird`) VALUES
	(1, 0, 10, 'Purple rumped Sunbird or smaller'),
	(2, 10, 23, 'Between Sunbird and Indian Myna'),
	(3, 23, 30, 'Indian Myna'),
	(4, 30, 43, 'Between Myna and Crow'),
	(5, 43, 43, 'Crow'),
	(6, 43, 150, 'Between Crow and Spot billed Pelican'),
	(7, 150, 255, 'Spot billed Pelican size or Bigger');
/*!40000 ALTER TABLE `x_birdsizes` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
